name: Development Deployment

on:
  push:
    branches: [ "develop" ]

jobs:
    transaction-api:
        name: deploy-transaction-api
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3       
        - name: Build the Docker image
          #working-directory: src/PrimeElectronics.API
          run: docker build . -t sawdykdocker/elevani_trans_dev_api:latest -f docker/transaction-api/Dockerfile

        - name: Log into Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Push the image to Docker Hub
          run: docker push sawdykdocker/elevani_trans_dev_api:latest

        - name: Pull the image to VM
          uses: appleboy/ssh-action@v1.0.0
          with:
            host: ${{ secrets.DEV_VPS_IP }}
            username: ${{ secrets.DEV_VPS_USER }}
            password: ${{ secrets.DEV_VPS_PASSWORD }}
            script: |
              docker image prune --all
              docker stop elevani_trans_dev_api || true
              docker rm elevani_trans_dev_api -f || true
              docker rmi sawdykdocker/elevani_trans_dev_api -f || true
              docker image pull sawdykdocker/elevani_trans_dev_api:latest
              cd /root/ElevaniApp/Backend/TransactionAPI
              docker compose up -d #run in detach mode

    admin-api:
        name: deploy-admin-api
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3       
        - name: Build the Docker image
          #working-directory: src/PrimeElectronics.API
          run: docker build . -t sawdykdocker/elevani_admin_dev_api:latest -f docker/admin-api/Dockerfile

        - name: Log into Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Push the image to Docker Hub
          run: docker push sawdykdocker/elevani_admin_dev_api:latest

        - name: Pull the image to VM
          uses: appleboy/ssh-action@v1.0.0
          with:
            host: ${{ secrets.DEV_VPS_IP }}
            username: ${{ secrets.DEV_VPS_USER }}
            password: ${{ secrets.DEV_VPS_PASSWORD }}
            script: |
              docker image prune --all
              docker stop elevani_admin_dev_api || true
              docker rm elevani_admin_dev_api -f || true
              docker rmi sawdykdocker/elevani_admin_dev_api -f || true
              docker image pull sawdykdocker/elevani_admin_dev_api:latest
              cd /root/ElevaniApp/Backend/AdminAPI
              docker compose up -d #run in detach mode

    gratip-job:
        name: deploy-gratip-job
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3      
        - name: Build the Docker image
          #working-directory: src/PrimeElectronics.API
          run: docker build . -t sawdykdocker/elevani_gratip_dev_job:latest -f docker/gratip-job/Dockerfile

        - name: Log into Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Push the image to Docker Hub
          run: docker push sawdykdocker/elevani_gratip_dev_job:latest

        - name: Pull the image to VM
          uses: appleboy/ssh-action@v1.0.0
          with:
            host: ${{ secrets.DEV_VPS_IP }}
            username: ${{ secrets.DEV_VPS_USER }}
            password: ${{ secrets.DEV_VPS_PASSWORD }}
            script: |
              docker image prune --all
              docker stop elevani_gratip_dev_job || true
              docker rm elevani_gratip_dev_job -f || true
              docker rmi sawdykdocker/elevani_gratip_dev_job -f || true
              docker image pull sawdykdocker/elevani_gratip_dev_job:latest
              cd /root/ElevaniApp/Backend/GratipJob
              docker compose up -d #run in detach mode

    payagency-job:
        name: deploy-payagency-job
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3      
        - name: Build the Docker image
          #working-directory: src/PrimeElectronics.API
          run: docker build . -t sawdykdocker/elevani_payagency_dev_job:latest -f docker/payagency-job/Dockerfile

        - name: Log into Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Push the image to Docker Hub
          run: docker push sawdykdocker/elevani_payagency_dev_job:latest

        - name: Pull the image to VM
          uses: appleboy/ssh-action@v1.0.0
          with:
            host: ${{ secrets.DEV_VPS_IP }}
            username: ${{ secrets.DEV_VPS_USER }}
            password: ${{ secrets.DEV_VPS_PASSWORD }}
            script: |
              docker image prune --all
              docker stop elevani_payagency_dev_job || true
              docker rm elevani_payagency_dev_job -f || true
              docker rmi sawdykdocker/elevani_payagency_dev_job -f || true
              docker image pull sawdykdocker/elevani_payagency_dev_job:latest
              cd /root/ElevaniApp/Backend/PayAgencyJob
              docker compose up -d #run in detach mode
    
